# Generated by Django 3.2.3 on 2021-06-17 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='title',
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AddField(
            model_name='ratings',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratings',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
