# Generated by Django 3.2.3 on 2022-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_markrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='markrequest',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
