# Generated by Django 3.2.3 on 2022-05-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_markrequest_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markrequest',
            name='profile',
        ),
    ]
