# Generated by Django 3.2.3 on 2022-05-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='no authors', max_length=300),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='no description', max_length=400),
        ),
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.CharField(default='no preview', max_length=300),
        ),
    ]
