# Generated by Django 3.2.3 on 2022-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendationBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('books', models.ManyToManyField(to='core.Book')),
            ],
        ),
    ]
